"""Daily sanitized export consumer.

Reads the pre-calculated MarketPulse payload from
``/data/static_site_payloads/latest_marketpulse.json``.  This file is
generated by the daily export job and contains all scores, components,
and regime information required by the public website.

This provider enables the frontend to display data **without any live
Bloomberg access** or real-time API calls.  It is the primary data
source for the public-facing website and embeddable widgets.

Export format
-------------
See ``SPEC.md`` section 8 for the full JSON schema.  Top-level keys::

    {
      "generated_at": "2026-01-15T16:30:00Z",
      "marketpulse": {
        "market": "sp500",
        "timestamp": "...",
        "composite": {"score": 67, "regime": "mp4_risk_on", ...},
        "classic": {"score": 72, ...},
        "narrative": {"score": 58, ...},
        "positioning": {"score": 71, ...},
        "confidence": 85,
        "explanation": "...",
        "components": [...],
        "data_quality": {...}
      }
    }
"""

from __future__ import annotations

import json
import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

import pandas as pd

from backend.domain.article import Article, SocialPost
from backend.domain.source import SourceStatus
from backend.providers.base import BaseProvider

logger = logging.getLogger(__name__)

_DEFAULT_PAYLOAD_PATH = Path("/data/static_site_payloads/latest_marketpulse.json")


class DailyExportProvider(BaseProvider):
    """Provider that reads the daily static export payload.

    This is the **primary data source** for the public website.  It
    requires no API keys, no Bloomberg Terminal, and no real-time data
    feeds — just a JSON file produced by the daily export job.
    """

    name: str = "daily_export"
    tier: str = "public"

    def __init__(self, payload_path: Optional[Path] = None) -> None:
        self.payload_path = payload_path or _DEFAULT_PAYLOAD_PATH
        self._payload: Optional[Dict[str, Any]] = None
        self._last_fetch: Optional[datetime] = None
        self._error_count: int = 0
        self._load_payload()

    # ── internal helpers ──────────────────────────────────────────────

    def _load_payload(self) -> None:
        """Eagerly load the payload file if it exists."""
        if not self.payload_path.exists():
            logger.debug(
                "Daily export payload not found at %s", self.payload_path
            )
            return
        try:
            with open(self.payload_path, "r", encoding="utf-8") as fh:
                self._payload = json.load(fh)
            self._last_fetch = datetime.now(timezone.utc)
            gen_at = self._payload.get("generated_at", "unknown")
            logger.info(
                "DailyExportProvider loaded payload (generated: %s)", gen_at
            )
        except (json.JSONDecodeError, OSError) as exc:
            self._error_count += 1
            logger.warning("Failed to load daily export payload: %s", exc)
            self._payload = None

    def _get_marketpulse(self) -> Optional[Dict[str, Any]]:
        """Return the nested marketpulse object from the payload."""
        if self._payload is None:
            return None
        return self._payload.get("marketpulse")

    def _generated_at(self) -> Optional[datetime]:
        """Parse the payload generation timestamp."""
        if self._payload is None:
            return None
        ts_str = self._payload.get("generated_at")
        if not ts_str:
            return None
        try:
            return datetime.fromisoformat(ts_str.replace("Z", "+00:00"))
        except (ValueError, TypeError):
            return None

    # ── BaseProvider implementation ───────────────────────────────────

    async def get_price_history(
        self,
        ticker: str,
        days: int = 252,
    ) -> Optional[pd.DataFrame]:
        """Price history is not stored in the daily export — return None."""
        return None

    async def get_current_quote(
        self,
        ticker: str,
    ) -> Optional[Dict[str, Any]]:
        """Return composite score and regime as a synthetic quote.

        Maps the headline composite score into the quote dict shape so
        downstream consumers can display it.
        """
        mp = self._get_marketpulse()
        if mp is None:
            return None
        composite = mp.get("composite", {})
        return {
            "price": float(composite.get("score", 0)),
            "change": float(composite.get("change_1d", 0)),
            "change_percent": float(composite.get("change_1d", 0)),
            "volume": 0,
            "timestamp": self._generated_at() or datetime.now(timezone.utc),
        }

    async def get_breadth_data(
        self,
        market_id: str,
    ) -> Optional[Dict[str, Any]]:
        """Extract breadth component from the payload if present."""
        mp = self._get_marketpulse()
        if mp is None:
            return None
        components = mp.get("components", [])
        for comp in components:
            if comp.get("name") == "breadth":
                return {
                    "advancing": comp.get("advancing"),
                    "declining": comp.get("declining"),
                    "advancing_volume": comp.get("advancing_volume"),
                    "declining_volume": comp.get("declining_volume"),
                    "new_highs": comp.get("new_highs"),
                    "new_lows": comp.get("new_lows"),
                    "percent_above_ma_50": comp.get("percent_above_ma_50"),
                    "percent_above_ma_200": comp.get("percent_above_ma_200"),
                }
        return None

    async def get_options_data(
        self,
        ticker: str,
    ) -> Optional[Dict[str, Any]]:
        """Extract put/call component from the payload if present."""
        mp = self._get_marketpulse()
        if mp is None:
            return None
        components = mp.get("components", [])
        for comp in components:
            if comp.get("name") == "put_call":
                return {
                    "put_volume": comp.get("put_volume"),
                    "call_volume": comp.get("call_volume"),
                    "put_call_ratio": comp.get("put_call_ratio"),
                    "put_open_interest": comp.get("put_open_interest"),
                    "call_open_interest": comp.get("call_open_interest"),
                }
        return None

    async def get_credit_spreads(
        self,
        series_id: str = "BAMLH0A0HYM2",
    ) -> Optional[Dict[str, Any]]:
        """Extract credit spread component from the payload if present."""
        mp = self._get_marketpulse()
        if mp is None:
            return None
        components = mp.get("components", [])
        for comp in components:
            if comp.get("name") in ("credit_spreads", "hy_spread", "ig_spread"):
                return {
                    "hy_spread": comp.get("hy_spread"),
                    "ig_spread": comp.get("ig_spread"),
                    "timestamp": self._generated_at() or datetime.now(timezone.utc),
                }
        return None

    async def get_safe_haven_assets(
        self,
    ) -> Optional[Dict[str, Any]]:
        """Extract safe-haven component from the payload if present."""
        mp = self._get_marketpulse()
        if mp is None:
            return None
        components = mp.get("components", [])
        for comp in components:
            if comp.get("name") == "safe_haven":
                return {
                    "TLT": comp.get("TLT"),
                    "GLD": comp.get("GLD"),
                    "UUP": comp.get("UUP"),
                    "timestamp": self._generated_at() or datetime.now(timezone.utc),
                }
        return None

    async def get_news_articles(
        self,
        query: str = "stock market",
        limit: int = 20,
    ) -> List[Article]:
        """The daily export does not include raw articles — return empty list."""
        return []

    async def get_social_posts(
        self,
        query: str = "stock market",
        limit: int = 50,
    ) -> List[SocialPost]:
        """The daily export does not include raw social posts — return empty list."""
        return []

    async def get_flows_data(
        self,
        ticker: str = "SPY",
    ) -> Optional[Dict[str, Any]]:
        """Extract ETF flow component from the payload if present."""
        mp = self._get_marketpulse()
        if mp is None:
            return None
        components = mp.get("components", [])
        for comp in components:
            if comp.get("name") in ("etf_flows", "flows"):
                return {
                    "inflow": comp.get("inflow"),
                    "outflow": comp.get("outflow"),
                    "net_flow": comp.get("net_flow"),
                    "aum": comp.get("aum"),
                    "timestamp": self._generated_at() or datetime.now(timezone.utc),
                }
        return None

    async def get_source_status(self) -> SourceStatus:
        """Report availability based on whether the payload file was loaded."""
        available = self._payload is not None
        age_minutes = None
        gen_at = self._generated_at()
        if gen_at:
            age = datetime.now(timezone.utc) - gen_at
            age_minutes = int(age.total_seconds() / 60)
        return SourceStatus(
            provider=self.name,
            available=available,
            last_successful_fetch=self._last_fetch,
            error_count_24h=self._error_count,
            data_freshness_minutes=age_minutes,
            tier=self.tier,
        )
